# Generated by Django 5.1.2 on 2024-11-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("varient", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "petrol"),
                            ("diesel", "diesel"),
                            ("EV", "EV"),
                            ("CNG", "CNG"),
                        ],
                        default="petrol",
                        max_length=200,
                    ),
                ),
                ("running_km", models.PositiveIntegerField()),
                ("color", models.CharField(max_length=200)),
                ("price", models.PositiveIntegerField()),
                ("brand", models.CharField(max_length=200)),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("single", "single"),
                            ("seconds", "seconds"),
                            ("other", "other"),
                        ],
                        default="single",
                        max_length=200,
                    ),
                ),
            ],
        ),
    ]
